# Generated by Django 2.2.5 on 2020-02-22 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('streak_date', models.DateField(auto_now=True)),
                ('streak_user', models.CharField(max_length=256)),
                ('streak_mood', models.CharField(max_length=50)),
            ],
        ),
    ]
